# define FLASHING_LIGHTS_TYPE 1
# define SWITCH_TYPE 2
# define SWITCH_RETURN_TYPE 3

# define SECTOR_TYPE 4
# define SECTOR_RETURN_TYPE 5

# define DIRECTIONAL_SECTOR = 6
# define DIRECTIONAL_SECTOR_RETURN = 7
